language: node_js
node_js:
- '4.3'
script:
- npm install
- npm test
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: TRtiRELwiBnaZZM1alpJgj4HxEh+GNnmhAixIG9AJFFnQ9oAyd3PQrjjfDfLBxoeekscWzLLBZu6EDYmnnEPftEUfPs/SBSIQ4Mx1C3QYucDNaRml3zb1TtMsRGlEVhFC3HcqkBRgLXb7ZDJZEM19YyjlqeWolH8mTTqWyfX0g4JAnomczCJuq2fmOnLhFQzRWQx+4soJKUBz8joTfxOmjd1myUrXnUmym6mo+qYtMOZA8WTh8nzjWenm70hp4n1kCPpZ//LQFjgrdJDL4YkPaJMMRqybKHMiGqnLfAz/mZ+4b0Fw7ODZF9ax7lkUx1BSH9xgxicGFlSGlKMAN8ofdUAceH9RigMQ32BcnN5Ekl6GndafoGpIUvizXswn7PFY5qxBoExh0VBJtqtXxcFnV43RmHthtVo2q5po0sESwOVqFqHtRxHFfl3mF2+Ljxhd81O/RGTa1PsLO0Yci4+DJ0bbGUanConq4mtVhnjKETaqLJuZbZdYWDiEI84UnaXwuLmL99PZXCkYBLe5WgDntQZkyeGK8v7FzQZTy+DItylV1m/sb8KGDN5gIPACGknjpprSs4M12J5OnrN3flNHNhYPPzaMopezhocpL5jRtqjfOEkpvxNWUS9b91d3ZwJSqi/TZ6yXHpqmxL/YCoDWMtaN3yC67Uns5a3IMcl2qc=
  - secure: plF83gjFOSx53PEhJ1kdtbGHvYyWH/0C0wnURd+SSIbWqMe4CQpsOxe4VlcK3G7dOW4R/lpBxgW2csiq1CqMAPxKz/b6itaxK3d1lY2OblAK0qMi2DmFTIMz9p3QgbdgN3chHyLf3OmTyJLFq3fENJPZ40TjuYIRCAheKK90UC31iRe62oOCsU48V7vl17GsfQXTYSKeYGdxazjO4NF9C12C1pn5eXMXo1ou7h/QlXoNdT+YHUYd60ZnJui0ksaKbLa6vzSA2NvkFtUh2Yy8jF1UjIpV9ODrcCI8jqga7zut2jRHq6ayoPhTwzOnYULG14u3jrb0QrggtVlDhLuWxP251ayGs+3jS5R/VFbDZFqx/xOxzW2uLRR9Ezykm0Px25N5I2oaH3xVbogF2w7b107YZb6KiEMJVvKp9VtSSOevVZ/qBfPrgOhNBEe2Dym1BFxNMnY3GZFuwm7wr713l8Yr7zZRZW4MRoHhVnYWY3R9bnpoHfAmU5Vb2tcsSg9q0OoItoLEwMk4lbja5vEIqwg1QGRnzSC1KqSp/eqjPLNzMTXF/O3n/m2/3J2f7FzvQBxhTBvwNIITppR9n4sNwin69EG4IUyMjHHsKOwIp+zG07J/WOrYKG9MXZM0qXRH1zApWXDIJkaVRWZdmKT4ZQxWEO+fWfgXZh7jaAJJ2qw=
